// GENERATED by massif.scripts.survey_ign_symbols — do not edit by hand.
//
// Huts IGN's basemap already draws a symbol for, from z13. The map
// suppresses its own house for these at that zoom and above, so their
// cartography is not competing with a second one; every other hut keeps
// ours, because IGN draws nothing there at any zoom.
//
// 29 of 59 huts, surveyed at z15.
export const IGN_SYMBOLISED: ReadonlySet<string> = new Set([
  "abri-simond",
  "abri-vallot",
  "auberge-du-truc",
  "bivacco-ettore-canzio",
  "cabane-de-la-tour-rouge",
  "cabane-des-rognes",
  "chalet-du-caf-contamines",
  "refuge-albert-1er",
  "refuge-dargentiere",
  "refuge-de-bellachat",
  "refuge-de-l-envers-des-aiguilles",
  "refuge-de-la-charpoua",
  "refuge-de-leschaux",
  "refuge-de-miage",
  "refuge-de-plan-glacier",
  "refuge-de-tre-la-tete",
  "refuge-des-conscrits",
  "refuge-des-cosmiques",
  "refuge-des-grands-mulets",
  "refuge-du-couvercle",
  "refuge-du-fioux",
  "refuge-du-gouter",
  "refuge-du-nid-d-aigle",
  "refuge-du-plan-de-laiguille",
  "refuge-du-requin",
  "refuge-durier",
  "refuge-robert-blanc",
  "refuge-tete-rousse",
  "refuge-torino",
]);
